### ISSUE TITLE
[Proposal] True documents pseudo-random shuffling on dataset annotation

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#1113]
Feature description
---------
As noted in https://github.com/doccano/doccano/pull/1072#discussion_r531214151, documents shuffling on dataset annotation is not pseudo-random because "randomization takes a long time".

Ok, that code shuffles the whole dataset. But in UI, on Annotation page, we get 20 documents per batch. So we have to shuffle 20 documents per request, only.

Proposal: to remove that mechanism and implement more simple and more pseudo-random instead.

Related: #1072, https://github.com/doccano/doccano/pull/1072#discussion_r531214151, #1099.

**Comment by fjen** [comment]
What do you mean with "20 documents per batch"? I don't know where this number comes from or what kind of batching you're referring to.

Could you please be more precise with your proposal? The current mechanism is already very simple and pseudo-random. Maybe give an example why the current approach is not sufficient and how it should be instead.

**Comment by kuraga** [comment]
@fjen ,

> What do you mean with "20 documents per batch"? I don't know where this number comes from or what kind of batching you're referring to.

1. Go to Annotation page.
2. You're on first document.
3. Turn off Internet.
4. You're able to switch 19 next documents without internet.
5. On 21st document an HTTP request will be fired.

**Comment by Dynnammo** [comment]
I have a question that may be related to this issue : I imported a batch of 700 sequence for text classification, and as I choose to annotate them in random orders, I remarked that they weren't has "shuffed" as wanted : let's say I have annotations with ID 1 ... 700.

When I clicked on "annotate on random order", it displayed annotations in gap of 6 : 1, 6, 12, 18 etc. which is not quite random since the import we made had some biases in the order annotations are in the file.
