### ISSUE TITLE
[Question] on pip installation... files and configuration

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#1232]
On pip installation, which files does doccano create? Where db is stored?

How to set up admin user and password?

I don't see this in readme...

**Comment by johann-petrak** [comment]
Maybe the info for this issue is helpful to you? 
https://github.com/doccano/doccano/issues/1192 

The database gets created as part of running the `doccano` command (which can take arguments for setting an admin password), but it is also possible to create the database using the commands I show in that issue so that one can run doccano with gunicorn subsequently, however that creates a *different* database in app subdirectory.

**Comment by kuraga** [comment]
@johann-petrak , thanks!

Migrated to #1237.
