### ISSUE TITLE
Where is the source code for v-annotator?

### ISSUE THREAD

**Issue by jhoobergs** [doccano/doccano#1711]
Feature description
---------
I would like to extend the doccano source code for my specific context, but I need to make changes to the code of v-annotator but I can't find it anywhere?

So i would like to have the 'feature' v-annotator' source code 😅

**Comment by Hironsan** [comment]
It's a private repository. Only published as an npm package.

**Comment by jhoobergs** [comment]
I assumed so. What is the reason for this?

**Comment by Rieko-I** [comment]
I have a question because it seems that the status has changed and it is now a public repository.

[doccano/v-annotatir](https://github.com/doccano/v-annotator)

This repository does not have an MIT license.
Do you have any plans to grant the MIT license?

It would be appreciated if it could be customized.

**Comment by Hironsan** [comment]
@Rieko-I I just added a license.

**Comment by Rieko-I** [comment]
@Hironsan Thank you! I appreciate it.
