### ISSUE TITLE
Feature request: Add Auto-labeling

### ISSUE THREAD

**Issue by erip** [doccano/doccano#191]
### Describe the problem

To help annotators, the system should adapt as labels are added to sentences.

As an initial task, I think NER autolabeling makes most sense. Currently the system has no dependencies on a tool for training NER models (like SpaCy or Flair), so it's worth discussion about how to prevent a user from being locked in with one or the other. It's also unclear how and when these models should be trained (online? minibatching?). How can a user specify a base model (or language) from which to begin training? 

I think this issue can serve as a good place for discussion.

**Comment by icoxfog417** [comment]
Thank you for the feature request! We already discussing about it at #6, but it will be good timing to summarize the discussion about auto labeling (because auto-labeling would be one of the most important feature of next version doccano).

**Why we need auto-labeling?**

discribed at [Feature Idea](https://github.com/chakki-works/doccano/projects/2#card-16404963)

* For reducing human labeling cost drastically.

If labels are automatically set, only the users have to do is check & edit these.

**How to make auto-labeling model**

There are mainly 2 approaches.

1. Transfer learning setting
   * Prepare the pre-trained model, and transfer it by annotated data.
2. Semi-supervised setting
   * Train the model by annotated label gradually.

And we can use active learning when selecting annotation target data (more than select randomly).

|                                            | use trained model? | choose target data? |
|--------------------------------------------|--------------------|---------------------|
| 1. Transfer learning                          | o                  | x                   |
| 2. Transfer learning + Active Learning        | o                  | x                   |
| 3. Semi-supervised learning (Few-shot)                   | x                  | x                   |
| 4. Semi-supervised learning + Active Learning | x                  | o                   |

In recent research, the effectiveness of semi-supervised/active learning setting is a little problematic.

* [How transferable are the datasets collected by active learners?](https://arxiv.org/abs/1807.04801)
* [When Semi-Supervised Learning Meets Transfer Learning: Training Strategies, Models and Datasets](https://arxiv.org/abs/1812.05313)
* [Realistic Evaluation of Deep Semi-Supervised Learning Algorithms](https://arxiv.org/abs/1804.09170)

So we have to think about how to implement auto-labeling carefully.

**How to cooperate auto-labeling model**

doccano is based on Web-API based architecture, so you can label the data by external model from API. 

[example here](https://github.com/chakki-works/doccano/issues/6#issuecomment-489924577)

**Comment by erip** [comment]
Something else that might be worth exploring: using stream processing might make a lot of sense for actual deployment. Stream processing frameworks like Kafka give the user flexibility to window a certain number of events (like `LabeledSentenceIngressed`) and after the window size has been met, retrain in a minibatch. It also allows you to easily do A/B testing or blue-green deployments of models.

**Comment by c-w** [comment]
Instead of directly depending on Kafka, I'd recommend to instead use an abstraction framework like [kombu](https://github.com/celery/kombu) which lets the developer pick from a wide range of queue implementations such as e.g. AWS SQS, Azure ServiceBus, RabbitMQ, Redis, SQLite, etc.

**Comment by bradfox2** [comment]
I'd also really like to see this feature.

If you've never used Rasa/Rasa-X, it may be worth checking out how their platform handles the user workflow around retraining/reapplication of new models on annotated chat text.  I found it to be very intuitive.  They've developed a specialized few-shot learning model that does appear to work as promised.

**Comment by sahinbatmaz** [comment]
Looking forward for the feature.

**Comment by ddelange** [comment]
With [`doccano-client`](https://pypi.org/project/doccano-client/) released to PyPI, it is now possible to hand off the active learning part to an external actor (preferably with its own Django user to distinguish model annotations from user annotations), like a Jupyter Notebook on a remote machine (with GPUs). With a powerful machine available, it is not too much overhead to just periodically predict all to-be-annotated docs, instead of predicting the docs on the fly.

I made a generic PoC of such a set up for Sequence Labelling projects, which takes all checked docs, trains, and predics all unchecked docs:

https://gist.github.com/ddelange/35d219991d60606dfff034a3985bb0d1

This way, the architecture does not grow as complex as [AlpacaTag](https://github.com/INK-USC/AlpacaTag), and the user keeps full control over hypertuning and model architectures etc.

Plus, the Doccano server doesn't experience extra load from the training/inference!
