### ISSUE TITLE
Feature request: choose where to start annotation

### ISSUE THREAD

**Issue by vanxoo** [doccano/doccano#261]
### System information
- Windows 10
- Python Version: 3.6 

### Describe the problem
Hi, I think it should be possible to indicate at which document we want to resume annotation. For example, I have a dataset of several thousands articles and cannot annotate them all at once, and when I quit Doccano then come back it just brings me on the first document.

Hence I think that either Doccano should automatically restart on the last document you annotated, or that is should allow us to indicate a number at which we want to start.

Thanks!

**Comment by c-w** [comment]
Since https://github.com/chakki-works/doccano/pull/79 was merged, you should be able to copy or bookmark the URL and resume editing at that page (see screenshot below).

[![Screenshot showing offset state in URL](https://user-images.githubusercontent.com/1086421/51856321-6e0e1e00-22fd-11e9-8420-1204b8a3d3b7.png)](https://user-images.githubusercontent.com/1086421/51856321-6e0e1e00-22fd-11e9-8420-1204b8a3d3b7.png)

Related issues: https://github.com/chakki-works/doccano/issues/84, https://github.com/chakki-works/doccano/issues/58.

@icoxfog417 @Hironsan Given that this feature request comes up regularly, would you be interested in reconsidering an approach like what was proposed in https://github.com/chakki-works/doccano/pull/195?

**Comment by icoxfog417** [comment]
Other related issue #310. #14

**Comment by Hironsan** [comment]
![image](https://user-images.githubusercontent.com/6737785/69935919-a08a3800-1519-11ea-83d1-462ec6f7eb02.gif)

**Comment by icoxfog417** [comment]
It'll be hard to remember page numbers when annotation. It'll be better to check/bookmark data to go back after (from my annotation experience).

**Comment by Hironsan** [comment]
Actually, resume feature has already been supported.
