### ISSUE TITLE
[Bug Report] Dataset page: non-ASCII metadata is displayed as Unicode-escaped sequence

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#513]
Dataset page: non-ASCII metadata is displayed as Unicode-escaped sequence.

![image](https://user-images.githubusercontent.com/1063219/71439555-26f5fc00-270b-11ea-83ec-d589b284c4c4.png)

(UTF-8 metadata. Displaying at annotation page is correct.)

Doccano 1.0.2

**Comment by kuraga** [comment]
@c-w where to fix this in your mind? I'll try.

**Comment by c-w** [comment]
@kuraga This looks to be a bug with the v1 UI with which I haven't yet familiarized myself (for my use-cases, I'm sticking with the v0 UI for now). @Hironsan can perhaps provide pointers for the v1 UI.

**Comment by Hironsan** [comment]
Hello @kuraga,

I can display non-ascii characters:
![image](https://user-images.githubusercontent.com/6737785/73226900-fc3d0e80-41b4-11ea-878b-5026affea28b.png)

Could you please tell me an example of metadata to analyze the problem for me?

**Comment by kuraga** [comment]
@Hironsan ,
dataset (CSV):
```
text,label,metadata_ключ
"a text","a_label","metadata_значение"
```
result:
![image](https://user-images.githubusercontent.com/1063219/73249542-23e8a280-41c6-11ea-9d58-07f1037e269b.png)

**Comment by Hironsan** [comment]
Thank you @kuraga for the information.
It's really helpful.

# Analysis

The issue is caused by `json.dumps` function in `FileParser`:
https://github.com/doccano/doccano/blob/1745821b2e484dc35b79959473a68070c8b5e3ae/app/api/utils.py#L361

When we upload a file, `FileParser` parses it and changes metadata to JSON string by `json.dumps`. By default, it escapes Unicode strings due to `ensure_ascii=True` argument:

```python
>>> import json
>>> json.dumps('metadata_значение')
'"metadata_\\u0437\\u043d\\u0430\\u0447\\u0435\\u043d\\u0438\\u0435"'
```

# Quick-fix solution

Use `ensure_ascii=True`:

```python
>>> json.dumps('metadata_значение', ensure_ascii=False)
'"metadata_значение"'
```

![image](https://user-images.githubusercontent.com/6737785/73256858-0c310e80-4206-11ea-91d5-1896f6102e15.png)

**Comment by kuraga** [comment]
@Hironsan , thanks!

But you pointed to `ExcelParser`'s method (which derives from `FileParser`). And there are other `json.dumps` in sibling classes.

Let's add a common FileParser`'s (static) method `encode_meta`?
