### ISSUE TITLE
[Question] About done/undone and checked/unchecked filters and users

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#525]
I don't understand filter mechanics... Filter "Done" shows only documents annotated _by current user_. Right? So filter "Undone" shows all documents _didn't annotated by current user_ (or maybe "unchecked ..."?).

But why? Why does Alice sees documents Bob has already annotated (even with "Undone" filter)?

**Comment by c-w** [comment]
Having Alice and Bob by default not see each other's work is useful in situations where you wish to collect multiple judgments on a given task without annotators influencing each other. If you wish that instead Alice and Bob to share progress and see each other's documents to avoid duplicate work, you can try using the "share annotations across all users" option (see https://github.com/doccano/doccano/pull/318).

**Comment by kuraga** [comment]
@c-w hm... I can check 9th Jan only but I turned this option... (maybe #519 but I turned it on via Django Admin).

And: does "checked" state play here?

**Comment by kuraga** [comment]
@c-w update: Alice sees annotations of Bob! But Alice can't filter out (I.e. hide automatically) these documents.

**Comment by c-w** [comment]
Looking into this briefly: [AnnotationList](https://github.com/doccano/doccano/blob/72cafaf881aa239393566278613a725c35b60ee8/app/api/views.py#L180-L181) respects the `project.collaborative_annotation` property. However, it looks like [DocumentList](https://github.com/doccano/doccano/blob/72cafaf881aa239393566278613a725c35b60ee8/app/api/views.py#L145-L152) and [DocumentFilter](https://github.com/doccano/doccano/blob/72cafaf881aa239393566278613a725c35b60ee8/app/api/filters.py#L12-L23) do not currently respect the property.

I suspect the fix for the behavior you're seeing would be to adjust the filter query in DocumentFilter to take the document's project's collaborative annotation flag into consideration. Currently we filter out any documents that have annotations by the current user. Instead if collaborative annotation is set, we should filter out documents that have annotations by any user.

**Comment by kuraga** [comment]
> I suspect the fix for the behavior you're seeing
> Instead we

@c-w so, is there a change this "fix" could be applied? :)

**Comment by kuraga** [comment]
@c-w change type to `bug` for consistency, please...

**Comment by c-w** [comment]
@kuraga I don't have admin privileges on the repo. @icoxfog417 can change the label.
