### ISSUE TITLE
[Bug Report] Filter selector's state is incorrect

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#530]
1. Select "Done" filter selector's state.
2. "Sign out".
3. "Sign in".
4. "Start annotation".
5. Filter behavior is: as "Done". Filter selector's state is: "All".

Doccano 1.0.2.

**Comment by Hironsan** [comment]
Hello, @kuraga 

Thank you for reporting the problem. I could reproduce it.

# Analysis

This is caused by `selected` variable in `FilterButton.vue` and `searchOptions` in the document store:

![image](https://user-images.githubusercontent.com/6737785/73225580-90f13d80-41b0-11ea-9780-c71a75faccd1.png)

* The initial state of `selected` and `searchOptions` is as above, where `selected=0` means the filter state is "All".
* Once we changed the filter option, `selected` is changed from 0 to 1 where `selected=1` means the filter state is "Done".
* When `selected` is changed, `searchOptions` variable in the document store is also changed as above.
* After we sign out and sign in, `selected` is initialized but `searchOptions` remains as is. This is because the former is a component local variable but the latter is a global variable by Vuex.
* As a result, the mismatch between filter state and behavior is occurred.
