### ISSUE TITLE
Can't login from the project link

### ISSUE THREAD

**Issue by huumq00731** [doccano/doccano#545]
1. Open browser(not logged in) and go to project link. 

for example: [http://IP:9740/projects/6](http://IP:9740/projects/6)

2. Log in with correct password

3. Incorrect pass msg will be show.

![image](https://user-images.githubusercontent.com/43772748/72784912-441bdd00-3c6d-11ea-8bc1-3f0d7dabca72.png)

Your Environment
---------
Doccano lastest code of master branch.

**Comment by kuraga** [comment]
I have strange issues like this but _not permanently_... But seems like it _sometimes_ appears if I signed in in Django Admin first...

**Comment by huumq00731** [comment]
> Can you login from the front page (http://IP:PORT) but can not log in from the project link?

Yes. I can login from the front page.
But when i share project link for another members. They can't login

**Comment by huumq00731** [comment]
I have been updated version of doccano to [lastest code of master branch].
not 1.0.2

**Comment by Hironsan** [comment]
# Problem and analysis

This is due to the authentication priority.

In Django Rest Framework, we can specify the authentication classes in `DEFAULT_AUTHENTICATION_CLASSES`. The more previous, the higher the priority. In doccano, `SessionAuthentication` is prior to `TokenAuthentication`.

https://github.com/doccano/doccano/blob/8818ab1171bc13a146807314e84d068c88615b9e/app/app/settings.py#L218-L221

When we sign in to the admin page,  we use `SessionAuthentication` as an authentication method, but when we sign in from the front page, we use `TokenAuthentication`. So if we sign in to the admin page before signing in from the front page, session id and csrftoken are stored in Cookies.
![image](https://user-images.githubusercontent.com/6737785/73151745-e0cbf800-410f-11ea-8a5f-568b60e62ec3.png)

If we sign in from the front page after we already have signed to the admin page, session id and csrftoken are sent to the server because they are stored in the cookies.
![image](https://user-images.githubusercontent.com/6737785/73151819-3c968100-4110-11ea-8cee-c89e1d81a0f3.png)

As a result, the server tries to accept the request as a session authentication. But after v1.0.0, we can sign in to the application only using token authentication. That's why the strange behavior is observed.

# Quick-fix solution

Comment out `SessionAuthentication` in `DEFAULT_AUTHENTICATION_CLASSES`. It does not prevent you from signing in to the admin page because the SessionAuthentication is different from Django admin's session authentication.

**Comment by kuraga** [comment]
@Hironsan are there some side-effects with this quick solution? Seems like I can't sign in (can't at all) with it:
```
backend_1   | Forbidden: /v1/auth-token
nginx_1     | 10.253.218.213 - - [06/Feb/2020:17:01:00 +0000] "POST /v1/auth-token HTTP/1.1" 403 58 "http://192.168.105.160:5001/auth" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" "-"
```
