### ISSUE TITLE
Make google-analytics configurable

### ISSUE THREAD

**Issue by harmw** [doccano/doccano#790]
It's not a bug, it's a feature! :p 

Just saw the following in `frontend/nuxt.config.js`:
```
  buildModules: [
    ['@nuxtjs/google-analytics', {
      id: 'UA-125643874-2'
    }]
  ],
```

Let's make this configurable, ie. being able to disable tracking user actions (using this `key`) or having a configurable setting to allow the user to use one's own GA key here to track doccano use in their own analytics setup.

**Comment by mattilyra** [comment]
Do I understand this correctly that `doccano` is actively tracking what my annotators are doing inside my organisation on my private data, with no way for me to turn the tracking off.

**Comment by Hironsan** [comment]
Not correct. doccano is not tracking what data you are using, which label your annotators are annotating and personal data like an e-mail address. Also, any project information like project name, labels, documents, members, annotation guidelines are not tracked because the information is not contained in URL, path, and query parameters. You can confirm it by reading the code.
