### ISSUE TITLE
[Enhancement request] Document and/or minimize production and development difference

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#810]
There are [/docker-compose.prod.yml](https://github.com/doccano/doccano/blob/73ac980186904b710dcf0e2563679bfdc52bc7a5/docker-compose.dev.yml) and [/docker-compose.dev.yml](https://github.com/doccano/doccano/blob/73ac980186904b710dcf0e2563679bfdc52bc7a5/docker-compose.dev.yml) recipes.

ReadMe says, they turn on different IP+ports. But what else?

Propose to document production and development differences.

**Comment by kuraga** [comment]
@andreizolotarev [commented](https://github.com/doccano/doccano/issues/733#issuecomment-635900337):

> @kuraga I agree with you that README just states about 2 options: prod and dev, and it is unclear for newcomers (especially, for some who are not so familiar with prod stuff) what option they should use. So, I think the main difference is that in `/docker-compose.prod.yml` NGINX is added, am I right, @Hironsan ?

**Comment by SiDevesh** [comment]
They seem to have way more differences than just the configuration.
The prod seems to be starting an older version which looks completely different and has quite a few issues already solved in the version that starts using docker-compose.yml.
This is very confusing since docker-compose.prod.yml sounds like it would just have config changes for production environment, not an entirely different application.

**Comment by kuraga** [comment]
@Hironsan [commented](https://github.com/doccano/doccano/pull/842#issuecomment-651432289):

> Instead of using the `Dockerfile` [as `docker-compose.prod.yml` does], `docker-compose.dev.yml` currently uses `node:13.2-alpine3.10` image directly.

**Comment by kuraga** [comment]
Outdated.
