### ISSUE TITLE
[Bug report] Incorrect current user name

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#840]
How to reproduce the behaviour
---------
I've  logged in as `a.kurakin` and, visually, I have `a.kurakin`'s permissions.

But I see:
![image](https://user-images.githubusercontent.com/1063219/84574986-c50d7980-adb2-11ea-8d5e-b7c9e197fcbc.png)
So, I'm supposed to be `admin`.
(Note: `admin` isn't something special here. Superuserness doesn't matter here.)

Behavior is reproduced. Ready to debug.

![screencast](https://user-images.githubusercontent.com/1063219/84595853-eaf25700-ae62-11ea-93c4-88525be28cbc.gif)

(Note: I've logged in both as `admin` and `a.kurakin` before, using the same browser window.)

Your Environment
---------

*   Operating System: Ubuntu 18.04.4 LTS
*   Python Version Used: system Python is 3.6.9
*   When you install doccano: 95344e562908cbc87609f5e15c9bdf019f3c99b9 or b4c99b5503e16bf0477bf0325ef0ec2d571e3981 - the same
*   How did you install doccano (Heroku button etc): Docker Compose

**Comment by icoxfog417** [comment]
Could you please clarify the reproduce procedure?

* When you login `a_user`, user name is `admin` always?
* If you have some precede procedure (ex: login `admin` before the `a_user` login), please let us know.

**Comment by kuraga** [comment]
@icoxfog417 , updated post above.

**Comment by cgill95** [comment]
This seems to have something to do with browser caching. When I login first with the `admin `account and afterwards with my account `chris` it still says admin like described above. Once I hit `CTRL `+ `F5` to refresh the page, the username changes to the correct one. I could reproduce this behavior multiple times.

OS:
Windows 10 with Google Chrome Version 83.0

**Comment by Hironsan** [comment]
I can reproduce the problem.

This is due to Vuex getter cache. If we access a getter by property styled access, the getter is cached. From the [Vuex docs](https://vuex.vuejs.org/guide/getters.html#property-style-access):
> Note that getters accessed as properties are cached as part of Vue's reactivity system.

To resolve this problem, we can use method style access. From the [Vuex docs](https://vuex.vuejs.org/guide/getters.html#method-style-access):
> Note that getters accessed via methods will run each time you call them, and the result is not cached.

In particular, we need to update `getUsername` in `store/auth.js` and `TheHeader.vue` in `components/organisms/layouts`:

https://github.com/doccano/doccano/blob/6b176d41e134ca59c8d415c99f4f99edcf6908d6/frontend/store/auth.js#L29-L31

to method style:

```javascript
getUsername: () => () => {
  return localStorage.getItem('username')
}
```

https://github.com/doccano/doccano/blob/6b176d41e134ca59c8d415c99f4f99edcf6908d6/frontend/components/organisms/layout/TheHeader.vue#L80

to method style access:

```html
<v-subheader>{{ getUsername() }}</v-subheader>
```
