### ISSUE TITLE
Non-administrator users can't see the left side navigation menu

### ISSUE THREAD

**Issue by br-dr3** [doccano/doccano#927]
It is kind of weird to anyone that is tagging to not see any option in left menu. This kind of confused people that we hired to tag some documents

- Annotator (non-admin) user
![image](https://user-images.githubusercontent.com/42852567/88314828-e5065600-cceb-11ea-86f6-df1effc109d4.png)

- Admin view
![image](https://user-images.githubusercontent.com/42852567/88314909-fd767080-cceb-11ea-9c2f-bd9a63c6537e.png)

Maybe Guideline and Dataset (if possible to avoid non-admin users to edit document's content) should be shown to all.

Superset of #270

**Comment by Hironsan** [comment]
I don't think annotators should be able to see the guideline page because they can see the guideline from the guideline button on the annotation page. The guideline page is only for project administrators.

On the other hand, I agree with you that annotators should be able to see the dataset page because it would be useful for annotators. I think it is necessary to hide some actions from annotators so I will consider how to solve it.

**Comment by br-dr3** [comment]
@Hironsan If annotators can already see guideline from the button in annotations page, I don't see any reason at all why they can't see ate Guideline menu too.. They should have read permission on this page, but they can't edit. 

I think guideline isn't the main root here. Maybe they should see all pages, but only read permission, or maybe they should see some of the pages, but all permission. But see anything can be confusing, Real taggers got confusing when saw doccano's home page

**Comment by Hironsan** [comment]
The purpose of the guideline page is to edit a guideline. It is the task of project administrators, not annotators. So they don't have to see the page. The other pages are also the same.

**Comment by br-dr3** [comment]
Well, maybe this page should be viewed for anyone and edited only by non-annotators?
