### ISSUE TITLE
restart doccano issue: UNIQUE constraint failed: auth_user.username

### ISSUE THREAD

**Issue by hhhwwwuuu** [doccano/doccano#965]
I installed doccano in win 10 with docker using the following instruction:
`docker pull doccano/doccano
docker container create --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -p 8000:8000 doccano/doccano`

I successfully install and login with admin account and guest account.
But,  once I stop doccano with following command:
`docker container stop doccano -t 5`

When I restarted the doccano with following command:
`docker container start doccano`

An error appeared:
`File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute

return Database.Cursor.execute(self, query, params)

django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username`

So, is there any mistake I did? how can I fix it?

Environment
---------

*   Operating System: win 10
*   Python Version Used: python 3.7
*   When you install doccano: 2020 July.
*   How did you install doccano (Heroku button etc): I was following the documentation with docker instruction.

**Comment by lamieceh** [comment]
Also having the same issue

**Comment by waterponey** [comment]
Also having the same issue

**Comment by waterponey** [comment]
Hi, I think it's linked to passing the admin login/password as environment variable at the "container create" step. 

If I keep it, then stop and start the container again, it'll fail.

If I remove this user (after creating and alternative admin), then stop and start the container, it'll restart with the [admin/password] existing again.

**Comment by waterponey** [comment]
Instead of doing

 `
docker container create --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -p 8000:8000 doccano/doccano

docker container start doccano
`

If I do 

`
docker container create --name doccano  -p 8000:8000 doccano/doccano

docker container start doccano

docker container exec doccano python app/manage.py create_admin --noinput --username="admin" --email="admin@example.com" --password="password"
`

This'll allow me to stop and start the container without any issues.

Alternatively maybe we could modify the create_admin.py to avoid this behaviour ?

**Comment by setu4993** [comment]
PR #987 that I just created should resolve this.
